# general build configuration
[build]
  base = "web/"
  publish = "web/public"
  command = "npm run build"

# redirect from blog.24paginas.com
[[redirects]]
  from = "https://blog.24paginas.com/*"
  to = "https://24paginas.com/:splat"
  status = 301
  force = true

# redirect tags -> etiquetas
[[redirects]]
  from = "https://24paginas.com/tags/*"
  to = "https://24paginas.com/etiquetas/:splat"
  status = 301
  force = true