# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 24 páginas
subtitle: 'Tebeos y otras cosas chachis'
description: 'Leer tebeos es de lo bueno lo mejor, de lo mejor lo superior'
keywords:
author: neverbot
language: es
timezone: ''

authors:
  neverbot:
    url: https://neverbot.com
  uncientovolando:
    url: https://instagram.com/uncientovolando
  hecdruiz:
    url: https://instagram.com/hecdruiz
  24paginas:
    url: https://24paginas.com

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://24paginas.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: etiquetas
archive_dir: archivo
category_dir: categorias
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year/:month/:day/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

post_asset_folder: true

# with hexo-renderer-markdown
# markdown:
#   plugins:
#     markdown-it-texmath:
#       disabled: true

# with  hexo-renderer-markdown-it
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
    - markdown-it-attrs
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
  images:
    lazyload: false
    prepend_root: false
    post_asset: false
  inline: false  # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD-MM-YYYY
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: 24paginas

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# hexo-generator-feed config
feed:
  enable: true
  type: ['atom', 'rss2']
  path: atom.xml/rss2.xml
  limit: 20
  hub:
  content: true
  # content_limit: 140
  # content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# giscus comments
giscus:
  repo: 24paginas/24paginas.com
  repoid: MDEwOlJlcG9zaXRvcnkxODI0NDE5ODA=
  category: Posts
  categoryid: DIC_kwDOCt_X_M4CeOZW
  mapping: title

related_posts:
  enabled: true
  # only calculate related_posts when env is production
  # npx hexo generate --pro
  # npx hexo server --pro
  enable_env_name: pro
  filter_threshold: 0.3
  related_count: 5
  weight:
      title: 0.05
      description: 0.05
      keywords: 0.01
      tags: 0.5
      categories: 0.1
      text: 0.1
  # stemmers:
  #   - en
  #   - ru
  # reserved:
  #   - asp.net
  #   - vs.net
  #   - ado.net
  #   - .net

sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  template: ./sitemap_template.xml
  template_txt: ./sitemap_template.txt
  rel: true
  tags: true
  categories: true
  